# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# base16-qutebrowser (https://github.com/theova/base16-qutebrowser)
# Base16 qutebrowser template by theova
# Gruvbox dark, hard scheme by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)

base00 = "#1d2021"
base01 = "#3c3836"
base02 = "#504945"
base03 = "#665c54"
base04 = "#bdae93"
base05 = "#d5c4a1"
base06 = "#ebdbb2"
base07 = "#fbf1c7"
base08 = "#fb4934"
base09 = "#fe8019"
base0A = "#fabd2f"
base0B = "#b8bb26"
base0C = "#8ec07c"
base0D = "#83a598"
base0E = "#d3869b"
base0F = "#d65d0e"

black = "#0a0b0d"
white = "#ffffff"
lightblue = "#9fe7e6"
blue = "#2bb9b8"
darkblue = "#398f8f"
red = "#cc0000"
green = "#138706"

c.tabs.indicator.width = 0

# set qutebrowser colors

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
c.colors.completion.fg = white

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = black

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = black

# Foreground color of completion widget category headers.
c.colors.completion.category.fg = white

# Background color of the completion widget category headers.
c.colors.completion.category.bg = red

# Top border color of the completion widget category headers.
c.colors.completion.category.border.top = red

# Bottom border color of the completion widget category headers.
c.colors.completion.category.border.bottom = red

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = black

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = white

# Top border color of the completion widget category headers.
c.colors.completion.item.selected.border.top = white

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = white

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = red

# Color of the scrollbar handle in the completion view.
c.colors.completion.scrollbar.fg = red

# Color of the scrollbar in the completion view.
c.colors.completion.scrollbar.bg = black

# Background color for the download bar.
c.colors.downloads.bar.bg = base00

# Color gradient start for download text.
c.colors.downloads.start.fg = base00

# Color gradient start for download backgrounds.
c.colors.downloads.start.bg = base0D

# Color gradient end for download text.
c.colors.downloads.stop.fg = base00

# Color gradient stop for download backgrounds.
c.colors.downloads.stop.bg = base0C

# Foreground color for downloads with errors.
c.colors.downloads.error.fg = base08

# Font color for hints.
c.colors.hints.fg = black

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
c.colors.hints.bg = white

# Font color for the matched part of hints.
c.colors.hints.match.fg = red

# Text color for the keyhint widget.
c.colors.keyhint.fg = white

# Highlight color for keys to complete the current keychain.
c.colors.keyhint.suffix.fg = red

# Background color of the keyhint widget.
c.colors.keyhint.bg = black

# Foreground color of an error message.
c.colors.messages.error.fg = white

# Background color of an error message.
c.colors.messages.error.bg = red

# Border color of an error message.
c.colors.messages.error.border = red

# Foreground color of a warning message.
c.colors.messages.warning.fg = white

# Background color of a warning message.
c.colors.messages.warning.bg = black

# Border color of a warning message.
c.colors.messages.warning.border = red

# Foreground color of an info message.
c.colors.messages.info.fg = white

# Background color of an info message.
c.colors.messages.info.bg = black

# Border color of an info message.
c.colors.messages.info.border = black

# Foreground color for prompts.
c.colors.prompts.fg = white

# Border used around UI elements in prompts.
c.colors.prompts.border = darkblue

# Background color for prompts.
c.colors.prompts.bg = black

# Background color for the selected item in filename prompts.
c.colors.prompts.selected.bg = red

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = white

# Background color of the statusbar.
c.colors.statusbar.normal.bg = black

# Foreground color of the statusbar in insert mode.
c.colors.statusbar.insert.fg = lightblue

# Background color of the statusbar in insert mode.
c.colors.statusbar.insert.bg = black

# Foreground color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.fg = lightblue

# Background color of the statusbar in passthrough mode.
c.colors.statusbar.passthrough.bg = black

# Foreground color of the statusbar in private browsing mode.
c.colors.statusbar.private.fg = red

# Background color of the statusbar in private browsing mode.
c.colors.statusbar.private.bg = black

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = lightblue

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = black

# Foreground color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.fg = lightblue

# Background color of the statusbar in private browsing + command mode.
c.colors.statusbar.command.private.bg = black

# Foreground color of the statusbar in caret mode.
c.colors.statusbar.caret.fg = lightblue

# Background color of the statusbar in caret mode.
c.colors.statusbar.caret.bg = black

# Foreground color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.fg = white

# Background color of the statusbar in caret mode with a selection.
c.colors.statusbar.caret.selection.bg = red

# Background color of the progress bar.
c.colors.statusbar.progress.bg = black

# Default foreground color of the URL in the statusbar.
c.colors.statusbar.url.fg = white

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = white

# Foreground color of the URL in the statusbar for hovered links.
c.colors.statusbar.url.hover.fg = lightblue

# Foreground color of the URL in the statusbar on successful load
# (http).
c.colors.statusbar.url.success.http.fg = white

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = white

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = white

# Background color of the tab bar.
c.colors.tabs.bar.bg = darkblue

# Color gradient start for the tab indicator.
#c.colors.tabs.indicator.start = base0D

# Color gradient end for the tab indicator.
#c.colors.tabs.indicator.stop = base0C

# Color for the tab indicator on errors.
#c.colors.tabs.indicator.error = base08

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = black

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = darkblue

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = black

# Background color of unselected even tabs.
c.colors.tabs.even.bg = darkblue

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = black

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = white

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = black

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = white

# Background color for webpages if unset (or empty to use the theme's
# color).
# c.colors.webpage.bg = base00

c.fonts.completion.category = "bold 12pt IBM 3270"
c.fonts.completion.entry = "11pt IBM 3270"
c.fonts.debug_console = "11pt IBM 3270"
c.fonts.downloads = "11pt IBM 3270"
c.fonts.keyhint = "11pt IBM 3270"
c.fonts.hints = "11pt IBM 3270"
c.fonts.messages.info = "11pt IBM 3270"
c.fonts.messages.error = "11pt IBM 3270"
c.fonts.messages.warning = "11pt IBM 3270"
c.fonts.prompts = "11pt IBM 3270"
c.fonts.statusbar = "12pt IBM 3270"
c.fonts.tabs = "12pt IBM 3270"

c.url.default_page = "https://old.reddit.com/r/news"
c.url.start_pages = "https://old.reddit.com/r/news"
